
### 主要根据文档，记录几个比较重要的api动作

官方文档例子地址[登陆登出流程控制](https://redux-saga-in-chinese.js.org/docs/advanced/NonBlockingCalls.html)

* yield([]) 同步 -- Promise.all
* yield.race([]) -- Promise.race
* fork
* cancel
* cancelled() 

> 想要同时执行两个请求

```js
// 错误写法，effects 将按照顺序执行
// 在上面的users fetch没结束时，不会进行下面的请求
const users = yield call(fetch, '/users'),
      repos = yield call(fetch, '/repos')
```

```js
// 正确写法, effects 将会同步执行
// 阻塞知道两个请求都有结果返回，或者其中任意一个抛出error被effect拒绝
const [users, repos] = yield [
  call(fetch, '/users'),
  call(fetch, '/repos')
]
```

> 多个任务只要最快那个

有两个使用场景
* 例如超时
* 在后台的循环任务中增加一个取消功能

```js
import { race, call, put } from 'redux-saga/effects'
import { delay } from 'redux-saga'

function* fetchPostsWithTimeout() {
  const {posts, timeout} = yield race({
    posts: call(fetchApi, '/posts'),
    timeout: call(delay, 1000)
  })

  if (posts)
    put({type: 'POSTS_RECEIVED', posts})
  else
    put({type: 'TIMEOUT_ERROR'})
}
```

第二个场景，`race`可以用来取消那些失败的 Effects


```js
/**
 * 在某个场景下开通了一个循环的background任务，并且是无限循环（比如：轮询等等）
 * 我们会有一个地方可以触发`cancel_taks` 来取消该任务。此时cancel_task竞争过了background
 * 同时会在background中抛出一个错误
*/
import { race, take, call } from 'redux-saga/effects'

function* backgroundTask() {
  while (true) { ... }
}

function* watchStartBackgroundTask() {
  while (true) {
    yield take('START_BACKGROUND_TASK')
    yield race({
      task: call(backgroundTask),
      cancel: take('CANCEL_TASK')
    })
  }
}
```


### 无阻塞调用之 fork & cancel

[官网文档](https://redux-saga-in-chinese.js.org/docs/advanced/NonBlockingCalls.html)

```js
import { take, call, put } from 'redux-saga/effects'
import Api from '...'

function* authorize(user, password) {
  try {
    // call的错误，会被catch捕捉
    // call是个阻塞动作，在得到返回结果前会阻塞掉后面的
    const token = yield call(Api.authorize, user, password)
    yield put({type: 'LOGIN_SUCCESS', token})
    return token
  } catch(error) {
    yield put({type: 'LOGIN_ERROR', error})
  }
}

// 在一个循环内，会首先监听login操作
// 如果error会抛错，返回undefined。跳出当前的循环，等待下一次login
// 返回成功会得到token 然后写入storage。并持续监听logout
// logout以后，清除storage，循环结束。等待下一次的login
function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUEST')
    const token = yield call(authorize, user, password)
    if(token) {
      yield call(Api.storeItem({token}))
      yield take('LOGOUT')
      yield call(Api.clearItem('token'))
    }
  }
}
```

**上段代码有一个情景，在login的req和获取res之间，用户就触发了logout操作。由于此时effect还被阻塞，无法监听到logout，导致此次操作无效**

以上这种情况应该用 `fork` 代替 `call`，使用户即使没有 `login`响应的情况下也可以 `logout`，使整个控制流更明显。

> `fork` 返回的是一个 `Task Object`，可以理解成一个任务指针。配合 `cancel` 可以取消掉这次任务

```js

import { take, call, put, cancelled } from 'redux-saga/effects'
import Api from '...'

function* authorize(user, password) {
  try {
    const token = yield call(Api.authorize, user, password)
    yield put({type: 'LOGIN_SUCCESS', token})
    yield call(Api.storeItem, {token})
    return token
  } catch(error) {
    yield put({type: 'LOGIN_ERROR', error})
  } finally {
    // 可以为取消错特殊处理，比如去掉storage
    if (yield cancelled()) {
      // ... put special cancellation handling code here
    }
  }
}

function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUEST')
    // fork return a Task object
    const task = yield fork(authorize, user, password)
    // logout和 login_error做并发任务处理，
    // 用take([])的意思是监听两个并发的action
    // 1、如果登录成功，只会出现logout
    // 2、如果登录error，会直接触发login_error的监听，从而进入下一个循环
    // 3、如果在login响应前就有监听到了logout的action，由于使用的fork，这里也会触发监听，取消task同时进入下一个循环
    const action = yield take(['LOGOUT', 'LOGIN_ERROR'])
    if(action.type === 'LOGOUT')
        // 取消 fork任务
      yield cancel(task)
    yield call(Api.clearItem('token'))
  }
}
```